name: Run Cosmology Simulation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run-simulation:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install numpy scipy matplotlib

    - name: Run simulation script
      run: |
        python main.py

    - name: Upload generated plot
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: cosmology-plot
        path: grafico.png