name: Run Simulations CI

on:
  push:
    branches: [ main ]
    paths:
      - '**.py'
      - 'notebooks/**'
  pull_request:
    branches: [ main ]
    paths:
      - '**.py'
      - 'notebooks/**'

jobs:
  run_simulation:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run simulation example
        run: |
          if [ -f run_simulations.py ]; then python run_simulations.py --example; else echo "Simulation script not found"; fi

      - name: Run tests
        run: |
          pytest -v || echo "No tests found"
