name: Testes com Pytest e Astropy

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install pytest astropy numpy scipy matplotlib

      - name: Rodar testes com pytest
        run: |
          pytest -v || true
